(function () {
  'use strict';

  const internals = window.__MeldexPwaDataAccessInternals;
  const handlers = window.__MeldexPwaDataAccessExtensions;
  if (!internals || !Array.isArray(handlers)) return;

  const {
    NOT_HANDLED,
    PWA_TRASH_DIR,
    _normalizeFolderPath,
    _joinPath,
    _dirname,
    _basename,
    _splitNameAndExt,
    _requirePwaProvider,
    _directoryHandle,
    _resolveEntryHandle,
    _listDirectoryEntries,
    _readJsonSafe,
    _fileStats,
    _validateItemName,
    _pathExists,
    _uniqueName,
    _moveConflictName,
    _moveEntry,
    _removeEntry,
    _classifyFileType,
    _iterateWorkspaceFiles,
    _requireUnlockedPath,
    _relocateReferences,
    _fnvFileId,
  } = internals;

  const SECRET_FILE = '_meldex/secrets/llm-api-keys.v1.json';
  const CALENDAR_STORE_DIR = '_calendar';
  const VERSION_FOLDER_DIR = '_meldex/versions/folders';
  const CALENDAR_DB_FIELDS = [
    'title', 'uid', 'ical_uid', 'start', 'end', 'all_day', 'color', 'location', 'url', 'description',
    'recurrence', 'alert_minutes', 'calendar_id', 'creator', 'members',
    'linkedEntryId', 'linkedEntryPath', 'linkedEntrySourceProperty', 'linkedAutoGenerated',
  ];
  const WORKSPACE_SCAN_EXCLUDES = ['_chat/', '_calendar/', '_meldex/', '_trash/', '_versions/', '_backup/', '_meldex_pwa/', 'node_modules/'];

  function _nowIso() {
    return new Date().toISOString();
  }

  function _randomId(prefix) {
    if (globalThis.crypto?.randomUUID) return crypto.randomUUID();
    return `${prefix || 'id'}_${Date.now().toString(36)}_${Math.random().toString(16).slice(2, 10)}`;
  }

  function _safeFileStem(value, fallback) {
    const text = String(value || fallback || '無題')
      .replace(/[\\/:*?"<>|\x00-\x1f]/g, '_')
      .replace(/\s+/g, ' ')
      .trim();
    return (text || fallback || '無題').slice(0, 100);
  }

  function _jsonValue(value) {
    return JSON.stringify(value == null ? '' : value);
  }

  function _truthy(value) {
    const text = String(value == null ? '' : value).trim().toLowerCase();
    return value === true || value === 1 || text === 'true' || text === '1' || text === 'yes';
  }

  function _parseFrontmatterValue(raw) {
    const value = String(raw || '').trim();
    if (!value) return '';
    if (value === 'true') return true;
    if (value === 'false') return false;
    if (value === 'null') return null;
    if (/^-?\d+(?:\.\d+)?$/.test(value)) return Number(value);
    if (/^[\[{"]/.test(value)) {
      try { return JSON.parse(value); } catch {}
    }
    return value.replace(/^['"]|['"]$/g, '');
  }

  function _parseFrontmatter(text) {
    const raw = String(text || '');
    const match = raw.match(/^\uFEFF?---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/);
    if (!match) return { frontmatter: {}, body: raw };
    const frontmatter = _yamlLiteObject(match[1]);
    match[1].split(/\r?\n/).forEach((line) => {
      if (/^\s/.test(line)) return;
      const idx = line.indexOf(':');
      if (idx <= 0) return;
      const key = line.slice(0, idx).trim();
      if (!key || Object.prototype.hasOwnProperty.call(frontmatter, key)) return;
      frontmatter[key] = _parseFrontmatterValue(line.slice(idx + 1));
    });
    return { frontmatter, body: raw.slice(match[0].length) };
  }

  function _frontmatterText(frontmatter, body) {
    const lines = ['---'];
    Object.entries(frontmatter || {}).forEach(([key, value]) => {
      if (!key || key.startsWith('_')) return;
      lines.push(`${key}: ${_jsonValue(value)}`);
    });
    lines.push('---', '');
    return lines.join('\n') + String(body || '');
  }

  async function _readText(provider, path, fallback) {
    try { return await provider.readText(_normalizeFolderPath(path)); }
    catch { return fallback == null ? '' : fallback; }
  }

  async function _readFrontmatterFile(provider, path) {
    return _parseFrontmatter(await _readText(provider, path, ''));
  }

  async function _writeFrontmatterFile(provider, path, frontmatter, body) {
    await provider.writeText(_normalizeFolderPath(path), _frontmatterText(frontmatter || {}, body || ''));
  }

  async function _requireUnlocked(provider, path, options) {
    if (typeof _requireUnlockedPath === 'function') return _requireUnlockedPath(provider, path, options || {});
    const checker = window.MeldexFileLockStore?.requireUnlocked;
    if (typeof checker === 'function') return checker(provider, path, options || {});
    return { ok: true, locked: false };
  }

  async function _folderNotePath(provider, folderPath) {
    const folder = _normalizeFolderPath(folderPath);
    const name = _basename(folder);
    if (!name) return '';
    const note = _joinPath(folder, name + '.md');
    const entry = await _resolveEntryHandle(provider, note);
    return entry?.kind === 'file' ? note : '';
  }

  async function _folderFrontmatter(provider, folderPath) {
    const note = await _folderNotePath(provider, folderPath);
    if (!note) return { path: '', frontmatter: {}, body: '' };
    const parsed = await _readFrontmatterFile(provider, note);
    return { path: note, ...parsed };
  }

  async function _ensureFolderNote(provider, folderPath, type) {
    const folder = _normalizeFolderPath(folderPath);
    const name = _basename(folder);
    if (!name) throw new Error('フォルダパスが不正です');
    await _directoryHandle(provider, folder, true);
    const note = _joinPath(folder, name + '.md');
    const existing = await _readFrontmatterFile(provider, note);
    const frontmatter = { ...(existing.frontmatter || {}) };
    if (!frontmatter.type) frontmatter.type = type || 'settings-db';
    await _writeFrontmatterFile(provider, note, frontmatter, existing.body || `# ${name}\n\n`);
    return note;
  }

  async function _databaseKind(provider, folderPath) {
    const note = await _folderFrontmatter(provider, folderPath);
    const type = String(note.frontmatter?.type || '');
    if (type === 'calendar-db') return 'calendar-db';
    if (type === 'settings-db') return 'settings-db';
    const entries = await _listDirectoryEntries(provider, folderPath).catch(() => []);
    for (const entry of entries) {
      if (entry.handle.kind !== 'file' || !entry.name.endsWith('.md') || entry.name.startsWith('_')) continue;
      const parsed = await _readFrontmatterFile(provider, _joinPath(folderPath, entry.name));
      if (parsed.frontmatter?.type === 'settings-entry') return 'settings-db';
      if (parsed.frontmatter?.type === 'calendar-event') return 'calendar-db';
    }
    return '';
  }

  async function _isDatabaseFolder(provider, folderPath) {
    return !!(await _databaseKind(provider, folderPath));
  }

  async function _findDatabaseFolders(provider, rootPath, maxDepth) {
    const result = [];
    async function walk(current, depth) {
      if (depth > maxDepth) return;
      let entries = [];
      try { entries = await _listDirectoryEntries(provider, current); } catch { return; }
      for (const entry of entries) {
        if (entry.handle.kind !== 'directory' || entry.name.startsWith('.') || entry.name.startsWith('_')) continue;
        const path = _joinPath(current, entry.name);
        const kind = await _databaseKind(provider, path);
        if (kind) result.push({ path, kind });
        else await walk(path, depth + 1);
      }
    }
    await walk(_normalizeFolderPath(rootPath), 0);
    return result;
  }

  function _normalizeCandidates(raw) {
    if (Array.isArray(raw)) return raw.map((candidate) => {
      if (candidate && typeof candidate === 'object' && !Array.isArray(candidate)) {
        const row = {
          value: candidate.value == null ? '' : String(candidate.value),
          status: String(candidate.status || '案'),
          note: String(candidate.note || ''),
          created: String(candidate.created || ''),
          relations: Array.isArray(candidate.relations) ? candidate.relations : undefined,
        };
        if (candidate.rich_html != null) row.rich_html = String(candidate.rich_html || '');
        return row;
      }
      return { value: candidate == null ? '' : String(candidate), status: '案', note: '', created: '' };
    });
    if (raw && typeof raw === 'object') return [_normalizeCandidates([raw])[0]];
    if (raw == null) return [];
    return [{ value: String(raw), status: '案', note: '', created: '' }];
  }

  function _normalizeCreateProperties(rawProps) {
    const out = {};
    Object.entries(rawProps || {}).forEach(([prop, value]) => {
      const rawList = Array.isArray(value) ? value : [value];
      out[String(prop)] = rawList.map((rawCandidate) => {
        const candidate = _normalizeCandidates([rawCandidate])[0] || { value: '', status: '採用', note: '', created: '' };
        const hasStatus = rawCandidate && typeof rawCandidate === 'object' && Object.prototype.hasOwnProperty.call(rawCandidate, 'status');
        const row = {
          value: candidate.value,
          status: hasStatus ? candidate.status : '採用',
          note: candidate.note || '',
          created: candidate.created || _nowIso(),
        };
        if (candidate.rich_html != null) row.rich_html = candidate.rich_html;
        return row;
      });
    });
    return out;
  }

  function _entityRowFromEntry(entryPath, entityName, frontmatter, filters) {
    const entity = {};
    if (frontmatter.id) entity._id = frontmatter.id;
    if (frontmatter.modified) entity._modified = String(frontmatter.modified);
    if (frontmatter.modified_by) entity._modified_by = String(frontmatter.modified_by);
    const properties = frontmatter.properties && typeof frontmatter.properties === 'object' && !Array.isArray(frontmatter.properties)
      ? frontmatter.properties
      : {};
    const statusFilters = filters && filters.length ? new Set(filters) : null;
    Object.entries(properties).forEach(([propName, rawList]) => {
      const rows = _normalizeCandidates(rawList)
        .map((candidate, index) => ({ candidate, index }))
        .filter(({ candidate }) => !statusFilters || statusFilters.has(candidate.status))
        .map(({ candidate, index }) => ({
          value: candidate.value || '',
          status: candidate.status || '案',
          note: candidate.note || '',
          file: entryPath,
          body: '',
          relations: Array.isArray(candidate.relations) ? candidate.relations : (Array.isArray(frontmatter.relations) ? frontmatter.relations : []),
          created: candidate.created || '',
          rich_html: candidate.rich_html || '',
          property: propName,
          candidate_index: index,
        }));
      if (rows.length) entity[propName] = rows;
    });
    return entity;
  }

  async function _readPivot(provider, dbPath, statusFilter) {
    const base = _normalizeFolderPath(dbPath);
    const entry = await _resolveEntryHandle(provider, base);
    if (!entry || entry.kind !== 'directory') throw new Error(`シートが見つかりません: ${base}`);
    const kind = await _databaseKind(provider, base);
    const filters = statusFilter ? String(statusFilter).split(',').map(v => v.trim()).filter(Boolean) : null;
    const entities = {};
    const properties = new Set();
    const entries = await _listDirectoryEntries(provider, base);
    for (const item of entries) {
      if (item.handle.kind !== 'file' || !item.name.endsWith('.md') || item.name.startsWith('_') || item.name === _basename(base) + '.md') continue;
      const filePath = _joinPath(base, item.name);
      const parsed = await _readFrontmatterFile(provider, filePath);
      const type = String(parsed.frontmatter?.type || '');
      if (type === 'settings-entry') {
        const row = _entityRowFromEntry(filePath, item.name.replace(/\.md$/i, ''), parsed.frontmatter, filters);
        Object.keys(row).filter(key => !key.startsWith('_')).forEach(key => properties.add(key));
        entities[item.name.replace(/\.md$/i, '')] = row;
      } else if (type === 'calendar-event') {
        const row = {};
        CALENDAR_DB_FIELDS.forEach((field) => {
          const value = parsed.frontmatter[field];
          if (value == null || value === '') return;
          properties.add(field);
          row[field] = [{
            value: field === 'members' && Array.isArray(value) ? JSON.stringify(value) : String(value),
            status: '採用',
            note: '',
            file: filePath,
            body: '',
            relations: [],
            created: parsed.frontmatter.created || '',
            property: field,
            candidate_index: 0,
          }];
        });
        entities[item.name.replace(/\.md$/i, '')] = row;
      }
    }
    return {
      entities,
      properties: [...properties].sort((a, b) => a.localeCompare(b, 'ja')),
      new_format: true,
      calendar_db: kind === 'calendar-db',
    };
  }

  async function _listDatabases(provider) {
    const folders = await _findDatabaseFolders(provider, '', 6);
    return folders.map(({ path, kind }) => ({
      path,
      name: _basename(path),
      relPath: path,
      rootName: 'vault',
      type: kind === 'calendar-db' ? 'calendar' : 'database',
    })).sort((a, b) => a.path.localeCompare(b.path, 'ja'));
  }

  async function _readEntity(provider, rawPath) {
    let path = _normalizeFolderPath(rawPath);
    let entry = await _resolveEntryHandle(provider, path);
    if (!entry && !/\.md$/i.test(path)) {
      path += '.md';
      entry = await _resolveEntryHandle(provider, path);
    }
    if (!entry || entry.kind !== 'file') throw new Error(`エントリが見つかりません: ${rawPath}`);
    const parsed = await _readFrontmatterFile(provider, path);
    if (parsed.frontmatter.type !== 'settings-entry') throw new Error('settings-entry ではありません');
    const properties = {};
    Object.entries(parsed.frontmatter.properties || {}).forEach(([prop, rawList]) => {
      properties[prop] = _normalizeCandidates(rawList).map((candidate, index) => ({
        value: candidate.value || '',
        status: candidate.status || '案',
        note: candidate.note || '',
        file: path,
        body: '',
        relations: Array.isArray(candidate.relations) ? candidate.relations : (Array.isArray(parsed.frontmatter.relations) ? parsed.frontmatter.relations : []),
        created: candidate.created || '',
        rich_html: candidate.rich_html || '',
        property: prop,
        candidate_index: index,
      }));
    });
    return {
      entity: _basename(path).replace(/\.md$/i, ''),
      path,
      properties,
      page_content: String(parsed.body || '').trim(),
      id: parsed.frontmatter.id || '',
      relations: Array.isArray(parsed.frontmatter.relations) ? parsed.frontmatter.relations : [],
    };
  }

  async function _writeEntity(provider, path, frontmatter, body) {
    frontmatter.modified = _nowIso();
    await _writeFrontmatterFile(provider, path, frontmatter, body || '');
  }

  async function _updateValue(provider, path, body) {
    const normalized = _normalizeFolderPath(path);
    const entry = await _resolveEntryHandle(provider, normalized);
    if (!entry || entry.kind !== 'file') {
      if (body?.skip_if_missing || body?.skipIfMissing) return { ok: true, skipped: true, missing: true };
      throw new Error(`エントリが見つかりません: ${normalized}`);
    }
    await _requireUnlocked(provider, normalized, { action: 'update-value' });
    const parsed = await _readFrontmatterFile(provider, normalized);
    const type = String(parsed.frontmatter.type || '');
    if (body && Object.prototype.hasOwnProperty.call(body, 'new_body')) {
      await _writeEntity(provider, normalized, parsed.frontmatter, body.new_body || '');
      return { ok: true };
    }
    if (type === 'calendar-event') {
      CALENDAR_DB_FIELDS.forEach((field) => {
        const key = 'new_' + field;
        if (body && Object.prototype.hasOwnProperty.call(body, key)) parsed.frontmatter[field] = body[key];
      });
      await _writeEntity(provider, normalized, parsed.frontmatter, parsed.body || '');
      return { ok: true };
    }
    if (type !== 'settings-entry') throw new Error('値更新対象が settings-entry ではありません');
    const prop = String(body?.property || '');
    if (!prop) throw new Error('property は必須です');
    const newProp = String(body?.new_property || prop).trim() || prop;
    const props = parsed.frontmatter.properties && typeof parsed.frontmatter.properties === 'object' ? parsed.frontmatter.properties : {};
    const list = _normalizeCandidates(props[prop]);
    let index = Number.isInteger(body?.candidate_index) ? body.candidate_index : Number(body?.candidate_index);
    if (!Number.isInteger(index) || index < 0 || index >= list.length) {
      if (body?._delete) return { ok: true, skipped: true };
      index = list.length;
      list.push({ value: '', status: '案', note: '', created: _nowIso() });
    }
    if (body?._delete) {
      list.splice(index, 1);
    } else {
      const candidate = list[index] || { value: '', status: '案', note: '', created: _nowIso() };
      if (Object.prototype.hasOwnProperty.call(body, 'new_value')) candidate.value = String(body.new_value ?? '');
      if (Object.prototype.hasOwnProperty.call(body, 'new_status')) candidate.status = String(body.new_status || '案');
      if (Object.prototype.hasOwnProperty.call(body, 'new_note')) candidate.note = String(body.new_note || '');
      if (Object.prototype.hasOwnProperty.call(body, 'new_rich_html')) {
        const richHtml = String(body.new_rich_html || '');
        if (richHtml) candidate.rich_html = richHtml;
        else delete candidate.rich_html;
      } else if (Object.prototype.hasOwnProperty.call(body, 'new_value')) {
        delete candidate.rich_html;
      }
      list[index] = candidate;
    }
    let resultIndex = index;
    if (!body?._delete && newProp !== prop) {
      const [candidate] = list.splice(index, 1);
      const targetList = _normalizeCandidates(props[newProp]);
      resultIndex = targetList.length;
      targetList.push(candidate);
      props[newProp] = targetList;
    }
    if (list.length) props[prop] = list;
    else delete props[prop];
    parsed.frontmatter.properties = props;
    await _writeEntity(provider, normalized, parsed.frontmatter, parsed.body || '');
    return { ok: true, path: normalized, property: body?._delete ? prop : newProp, candidate_index: resultIndex };
  }

  async function _addValue(provider, body) {
    const entryPath = _normalizeFolderPath(body?.entry_path || body?.folder_path || '');
    if (!entryPath) throw new Error('entry_path は必須です');
    const prop = String(body?.property || '');
    if (!prop) throw new Error('property は必須です');
    await _requireUnlocked(provider, entryPath, { action: 'add-value' });
    const parsed = await _readFrontmatterFile(provider, entryPath);
    if (parsed.frontmatter.type !== 'settings-entry') throw new Error('settings-entry ではありません');
    const props = parsed.frontmatter.properties && typeof parsed.frontmatter.properties === 'object' ? parsed.frontmatter.properties : {};
    const list = _normalizeCandidates(props[prop]);
    const candidate = {
      value: String(body?.value ?? ''),
      status: String(body?.status || '案'),
      note: String(body?.note || ''),
      created: _nowIso(),
    };
    if (body?.rich_html != null) candidate.rich_html = String(body.rich_html || '');
    list.push(candidate);
    props[prop] = list;
    parsed.frontmatter.properties = props;
    await _writeEntity(provider, entryPath, parsed.frontmatter, parsed.body || '');
    return { ok: true, path: entryPath, property: prop, candidate_index: list.length - 1 };
  }

  async function _createEntity(provider, body) {
    const parent = _normalizeFolderPath(body?.parent_path || '');
    const name = _safeFileStem(body?.name || '', '無題');
    if (!parent || !name) throw new Error('parent_path, name は必須です');
    await _requireUnlocked(provider, parent, { action: 'create-entity-parent' });
    await _ensureFolderNote(provider, parent, 'settings-db');
    const targetName = await _uniqueName(provider, parent, name, '.md');
    const path = _joinPath(parent, targetName + '.md');
    await _requireUnlocked(provider, path, { action: 'create-entity' });
    const now = _nowIso();
    await _writeFrontmatterFile(provider, path, {
      type: 'settings-entry',
      id: 'ent_' + _randomId('').replace(/[^a-z0-9]/gi, '').slice(0, 12),
      category: _basename(parent),
      created: now,
      created_by: String(body?.user || 'anonymous'),
      properties: _normalizeCreateProperties(body?.properties || {}),
      relations: [],
      source: body?.source || '',
      reviewed: body?.reviewed === true,
    }, '');
    return { ok: true, path };
  }

  async function _renameEntity(provider, body) {
    const path = _normalizeFolderPath(body?.path || '');
    const newName = _safeFileStem(body?.new_name || '', '');
    if (!path || !newName) throw new Error('path, new_name は必須です');
    const entry = await _resolveEntryHandle(provider, path);
    if (!entry) throw new Error(`エントリが見つかりません: ${path}`);
    await _requireUnlocked(provider, path, { action: 'rename-entity-source', includeDescendants: entry.kind === 'directory' });
    const dest = entry.kind === 'file'
      ? _joinPath(_dirname(path), newName + _splitNameAndExt(_basename(path)).ext)
      : _joinPath(_dirname(path), newName);
    if (dest !== path && await _pathExists(provider, dest)) throw new Error(`既に存在: ${newName}`);
    if (dest !== path) await _requireUnlocked(provider, dest, { action: 'rename-entity-destination', includeDescendants: entry.kind === 'directory' });
    if (dest !== path) await _moveEntry(provider, path, dest);
    const result = { ok: true, new_path: dest, file_id: _fnvFileId(dest) };
    if (dest !== path) result.relocate = await _relocateWorkspaceReferences(provider, path, dest);
    return result;
  }

  async function _dbMetadata(provider, path) {
    const target = _normalizeFolderPath(path);
    const note = await _folderFrontmatter(provider, target);
    const fm = note.frontmatter || {};
    return {
      actions: Array.isArray(fm.actions) ? fm.actions : [],
      backlinks: Array.isArray(fm.backlinks) ? fm.backlinks : [],
      style: fm.style || null,
      theme: fm.theme || null,
      property_types: fm.property_types && typeof fm.property_types === 'object' ? fm.property_types : {},
      property_layout: fm.property_layout || null,
      property_layout_templates: Array.isArray(fm.property_layout_templates) ? fm.property_layout_templates : [],
      publish: fm.publish || null,
      calendar_mapping: fm.calendar_mapping || null,
    };
  }

  async function _putDbMetadata(provider, path, body) {
    const target = _normalizeFolderPath(path);
    await _requireUnlocked(provider, target, { action: 'db-metadata' });
    await _ensureFolderNote(provider, target, 'settings-db');
    const notePath = await _folderNotePath(provider, target);
    const parsed = await _readFrontmatterFile(provider, notePath);
    const fm = { ...(parsed.frontmatter || {}) };
    [
      'type', 'category', 'roles', 'property_types', 'property_layout',
      'property_layout_templates', 'publish', 'actions', 'backlinks',
      'style', 'theme', 'calendar_mapping',
    ].forEach((key) => {
      if (body && Object.prototype.hasOwnProperty.call(body, key)) fm[key] = body[key];
    });
    if (!fm.type) fm.type = 'settings-db';
    await _writeFrontmatterFile(provider, notePath, fm, parsed.body || '');
    return { ok: true };
  }

  function _candidateMatches(candidate, field, operator, filterValue) {
    const target = field === 'status' ? candidate.status : candidate.value;
    const targetText = String(target == null ? '' : target);
    const filterText = String(filterValue == null ? '' : filterValue);
    if (operator === 'equals') return targetText === filterText;
    if (operator === 'not_equals') return targetText !== filterText;
    if (operator === 'contains') return targetText.includes(filterText);
    if (operator === 'not_contains') return !targetText.includes(filterText);
    if (operator === 'empty') return !targetText.trim();
    if (operator === 'not_empty') return !!targetText.trim();
    return false;
  }

  function _valuesMatch(values, field, operator, filterValue) {
    const list = Array.isArray(values) ? values : [];
    if (!list.length) return operator === 'empty' || operator === 'not_contains';
    if (operator === 'not_equals' || operator === 'not_contains') {
      return list.every(candidate => _candidateMatches(candidate, field, operator, filterValue));
    }
    return list.some(candidate => _candidateMatches(candidate, field, operator, filterValue));
  }

  async function _smartDb(provider, url) {
    const filters = JSON.parse(url.searchParams.get('filters') || '[]');
    const q = String(url.searchParams.get('q') || '').toLowerCase();
    const scope = _normalizeFolderPath(url.searchParams.get('scope') || '');
    const dbs = scope ? [{ path: scope }] : await _findDatabaseFolders(provider, '', 6);
    const matched = [];
    let totalEntities = 0;
    for (const db of dbs) {
      const dbPath = db.path || db;
      const pivot = await _readPivot(provider, dbPath, '');
      Object.entries(pivot.entities || {}).forEach(([entityName, props]) => {
        totalEntities += 1;
        if (q) {
          const haystack = [entityName];
          Object.values(props || {}).forEach((vals) => {
            if (Array.isArray(vals)) vals.forEach(v => haystack.push(v.value || ''));
          });
          if (!haystack.some(text => String(text).toLowerCase().includes(q))) return;
        }
        let ok = true;
        const matchedProps = {};
        filters.forEach((flt) => {
          if (!ok || !flt?.property) return;
          const values = props[flt.property] || [];
          if (!_valuesMatch(values, flt.field || 'value', flt.operator || 'contains', flt.value || '')) {
            ok = false;
            return;
          }
          matchedProps[flt.property] = values;
        });
        if (!ok) return;
        matched.push({
          name: entityName,
          path: _joinPath(dbPath, entityName + '.md'),
          db_path: dbPath,
          db_name: _basename(dbPath),
          root_name: 'vault',
          matched_props: filters.length ? matchedProps : props,
          created: '',
          modified: props._modified || '',
        });
      });
    }
    return {
      entities: matched,
      filter_properties: filters.map(f => f.property).filter(Boolean),
      total_dbs_scanned: dbs.length,
      total_entities_scanned: totalEntities,
    };
  }

  async function _globalIndex(provider) {
    const files = [];
    await _iterateWorkspaceFiles(provider, async (path, handle) => {
      const normalized = _normalizeFolderPath(path);
      if (_isWorkspaceScanExcluded(normalized)) return;
      const stats = await _fileStats(handle).catch(() => ({ size: 0, modified: '' }));
      const type = await _classifyFileType(provider, normalized, { allFiles: true }).catch(() => 'unknown');
      const ext = _splitNameAndExt(_basename(normalized)).ext.toLowerCase();
      files.push({
        name: _basename(normalized),
        category: type || 'other',
        root_name: 'vault',
        root_type: 'vault',
        ext,
        path: normalized,
        abs_path: normalized,
        size: stats.size || 0,
        modified: stats.modified || '',
        backlink_file_count: 0,
        backlink_board_count: 0,
        backlink_scriptnote_count: 0,
        backlink_page_count: 0,
      });
    }, '');
    files.sort((a, b) => String(b.modified || '').localeCompare(String(a.modified || '')));
    return { files, source_roots: [{ name: 'vault', type: 'vault' }], total: files.length };
  }

  function _calendarStorePath(name) {
    return _joinPath(CALENDAR_STORE_DIR, name + '.json');
  }

  async function _readStore(provider, name) {
    const data = await _readJsonSafe(provider, _calendarStorePath(name), []);
    return Array.isArray(data) ? data : [];
  }

  async function _writeStore(provider, name, rows) {
    await _directoryHandle(provider, CALENDAR_STORE_DIR, true);
    await provider.writeJson(_calendarStorePath(name), Array.isArray(rows) ? rows : []);
  }

  function _filterRows(rows, url, fields) {
    return rows.filter((row) => fields.every((field) => {
      const value = url.searchParams.get(field);
      return !value || String(row[field] || '') === value || (field === 'month' && String(row.date || '').startsWith(value));
    }));
  }

  function _dateInRange(value, start, end) {
    const text = String(value || '');
    if (start && text < start) return false;
    if (end && text > end) return false;
    return true;
  }

  async function _calendarList(provider, name, url) {
    const rows = await _readStore(provider, name);
    if (name === 'events') {
      const start = url.searchParams.get('start') || '';
      const end = url.searchParams.get('end') || '';
      const user = url.searchParams.get('user') || '';
      return rows.filter(row => (!user || row.user === user || row.creator === user || !row.user) && _dateInRange(row.start || row.due_date, start, end));
    }
    if (name === 'time') {
      const user = url.searchParams.get('user') || '';
      const from = url.searchParams.get('date_from') || '';
      const to = url.searchParams.get('date_to') || '';
      const taskId = url.searchParams.get('task_id') || '';
      return rows.filter(row => (!user || row.user === user) && (!taskId || row.task_id === taskId) && _dateInRange(row.timestamp, from, to));
    }
    if (name === 'shifts') return _filterRows(rows, url, ['user', 'month']);
    return _filterRows(rows, url, ['user', 'status', 'assignee', 'parent_id']);
  }

  async function _calendarCreate(provider, name, body) {
    const rows = await _readStore(provider, name);
    const now = _nowIso();
    const id = String(body?.id || _randomId(name));
    const row = { id, created: now, modified: now, ...(body || {}) };
    if (name === 'calendars') {
      row.name = row.name || 'マイカレンダー';
      row.color = row.color || '#569cd6';
      row.user = row.user || 'anonymous';
      row.visible = row.visible == null ? 1 : row.visible;
    }
    if (name === 'events') {
      row.title = row.title || '無題';
      row.user = row.user || row.creator || 'anonymous';
      row.creator = row.creator || row.user;
    }
    if (name === 'tasks') {
      row.title = row.title || '無題';
      row.status = row.status || 'todo';
      row.priority = row.priority || 'medium';
    }
    if (name === 'shifts') {
      row.user = row.user || 'anonymous';
      row.type = row.type || 'work';
      row.date = row.date || '';
    }
    const existingIdx = name === 'shifts' ? rows.findIndex(item => String(item.id) === String(id)) : -1;
    if (existingIdx >= 0) rows[existingIdx] = { ...rows[existingIdx], ...row, id: rows[existingIdx].id, modified: now };
    else rows.push(row);
    await _writeStore(provider, name, rows);
    if (name === 'shifts') await window.MeldexCloudShiftSync?.sync?.(provider, existingIdx >= 0 ? rows[existingIdx] : row);
    return { ok: true, id };
  }

  async function _calendarUpdate(provider, name, id, body) {
    const rows = await _readStore(provider, name);
    const idx = rows.findIndex(row => String(row.id) === String(id));
    if (idx < 0) throw new Error('対象が見つかりません');
    rows[idx] = { ...rows[idx], ...(body || {}), id: rows[idx].id, modified: _nowIso() };
    await _writeStore(provider, name, rows);
    if (name === 'shifts') await window.MeldexCloudShiftSync?.sync?.(provider, rows[idx]);
    return { ok: true };
  }

  async function _calendarDelete(provider, name, id) {
    const rows = await _readStore(provider, name);
    await _writeStore(provider, name, rows.filter(row => String(row.id) !== String(id)));
    if (name === 'shifts') await window.MeldexCloudShiftSync?.remove?.(provider, id);
    return { ok: true };
  }

  async function _calendarDbEvents(provider, dbPath) {
    const base = _normalizeFolderPath(dbPath);
    const rows = [];
    const entries = await _listDirectoryEntries(provider, base);
    for (const entry of entries) {
      if (entry.handle.kind !== 'file' || !entry.name.endsWith('.md') || entry.name === _basename(base) + '.md') continue;
      const filePath = _joinPath(base, entry.name);
      const parsed = await _readFrontmatterFile(provider, filePath);
      if (parsed.frontmatter.type !== 'calendar-event') continue;
      rows.push({
        ...parsed.frontmatter,
        id: entry.name.replace(/\.md$/i, ''),
        name: entry.name.replace(/\.md$/i, ''),
        path: filePath,
        body: String(parsed.body || '').trim(),
        members: Array.isArray(parsed.frontmatter.members) ? parsed.frontmatter.members : [],
      });
    }
    return rows.sort((a, b) => String(a.start || '').localeCompare(String(b.start || '')));
  }

  async function _calendarDbCreate(provider, body) {
    const dbPath = _normalizeFolderPath(body?.db_path || '');
    if (!dbPath) throw new Error('db_path は必須です');
    await _requireUnlocked(provider, dbPath, { action: 'calendar-db-create-parent' });
    await _ensureFolderNote(provider, dbPath, 'calendar-db');
    const title = _safeFileStem(body?.title || '無題', '無題');
    const stem = await _uniqueName(provider, dbPath, title, '.md');
    const path = _joinPath(dbPath, stem + '.md');
    await _requireUnlocked(provider, path, { action: 'calendar-db-create' });
    const now = _nowIso();
    await _writeFrontmatterFile(provider, path, {
      type: 'calendar-event',
      title: body?.title || title,
      uid: body?.uid || '',
      ical_uid: body?.ical_uid || body?.uid || '',
      start: body?.start || '',
      end: body?.end || '',
      all_day: _truthy(body?.all_day),
      color: body?.color || '#569cd6',
      location: body?.location || '',
      url: body?.url || '',
      description: body?.description || '',
      recurrence: body?.recurrence || '',
      alert_minutes: body?.alert_minutes ?? -1,
      calendar_id: body?.calendar_id || 'default',
      creator: body?.creator || body?.user || '',
      members: Array.isArray(body?.members) ? body.members : [],
      linkedEntryId: body?.linkedEntryId || '',
      linkedEntryPath: body?.linkedEntryPath || '',
      linkedEntrySourceProperty: body?.linkedEntrySourceProperty || '',
      linkedAutoGenerated: _truthy(body?.linkedAutoGenerated),
      created: now,
      modified: now,
    }, '');
    return { ok: true, id: stem, name: stem, path };
  }

  async function _calendarDbUpdate(provider, eventName, body) {
    const dbPath = _normalizeFolderPath(body?.db_path || '');
    const safeName = _safeFileStem(eventName, '');
    const path = _joinPath(dbPath, safeName + '.md');
    const parsed = await _readFrontmatterFile(provider, path);
    if (parsed.frontmatter.type !== 'calendar-event') throw new Error('イベントが見つかりません');
    await _requireUnlocked(provider, path, { action: 'calendar-db-update' });
    CALENDAR_DB_FIELDS.forEach((key) => {
      if (Object.prototype.hasOwnProperty.call(body || {}, key)) parsed.frontmatter[key] = body[key];
    });
    parsed.frontmatter.modified = _nowIso();
    let nextPath = path;
    const nextTitle = body?.title ? _safeFileStem(body.title, '') : '';
    if (nextTitle && nextTitle !== safeName) {
      nextPath = _joinPath(dbPath, nextTitle + '.md');
      if (await _pathExists(provider, nextPath)) throw new Error('同名のイベントが既に存在します');
      await _requireUnlocked(provider, nextPath, { action: 'calendar-db-rename-destination' });
    }
    await _writeFrontmatterFile(provider, path, parsed.frontmatter, parsed.body || '');
    if (nextPath !== path) await _moveEntry(provider, path, nextPath);
    const nextStem = _basename(nextPath).replace(/\.md$/i, '');
    return { ok: true, id: nextStem, name: nextStem, path: nextPath };
  }

  async function _calendarDbDelete(provider, eventName, dbPath) {
    const path = _joinPath(_normalizeFolderPath(dbPath), _safeFileStem(eventName, '') + '.md');
    const entry = await _resolveEntryHandle(provider, path);
    if (!entry) return { ok: true };
    await _requireUnlocked(provider, path, { action: 'calendar-db-delete' });
    await _directoryHandle(provider, PWA_TRASH_DIR, true);
    const dest = await _moveConflictName(provider, PWA_TRASH_DIR, _basename(path), true);
    await _moveEntry(provider, path, dest.path);
    return { ok: true, trash_path: dest.path };
  }

  function _icalDate(value, dateOnly) {
    const text = String(value || '');
    if (dateOnly || /^\d{4}-\d{2}-\d{2}$/.test(text)) return text.slice(0, 10).replace(/-/g, '');
    const zoned = /(?:Z|[+-]\d{2}:?\d{2})$/i.test(text);
    const parsed = zoned ? new Date(text) : null;
    const pad = value => String(value).padStart(2, '0');
    if (parsed && !Number.isNaN(parsed.getTime())) {
      return parsed.getUTCFullYear()
        + pad(parsed.getUTCMonth() + 1)
        + pad(parsed.getUTCDate())
        + 'T'
        + pad(parsed.getUTCHours())
        + pad(parsed.getUTCMinutes())
        + pad(parsed.getUTCSeconds())
        + 'Z';
    }
    const local = text.match(/^(\d{4})-?(\d{2})-?(\d{2})(?:[T\s](\d{2}):?(\d{2})(?::?(\d{2}))?)?/);
    if (local) {
      const [, y, mo, d, h = '00', mi = '00', s = '00'] = local;
      return `${y}${mo}${d}T${h}${mi}${s}`;
    }
    return text.replace(/[-:]/g, '').replace(/\.\d+/, '').replace(/[+-]\d{2}:?\d{2}$/i, '');
  }

  function _icalText(value) {
    return String(value || '')
      .replace(/\\/g, '\\\\')
      .replace(/\r?\n/g, '\\n')
      .replace(/,/g, '\\,')
      .replace(/;/g, '\\;');
  }

  function _icalExport(events) {
    const lines = ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//Meldex Cloud BETA//JA'];
    events.forEach((event) => {
      lines.push('BEGIN:VEVENT');
      lines.push('UID:' + _icalText(event.ical_uid || event.uid || event.id || event.name || _randomId('ev')));
      lines.push('SUMMARY:' + _icalText(event.title || event.name || '無題'));
      const dateOnly = _truthy(event.all_day) || /^\d{4}-\d{2}-\d{2}$/.test(String(event.start || ''));
      if (event.start) lines.push((dateOnly ? 'DTSTART;VALUE=DATE:' : 'DTSTART:') + _icalDate(event.start, dateOnly));
      if (event.end) lines.push((dateOnly ? 'DTEND;VALUE=DATE:' : 'DTEND:') + _icalDate(event.end, dateOnly));
      if (event.location) lines.push('LOCATION:' + _icalText(event.location));
      if (event.url) lines.push('URL:' + _icalText(event.url));
      if (event.description) lines.push('DESCRIPTION:' + _icalText(event.description));
      const rrule = _recurrenceToRrule(event.recurrence || '');
      if (rrule) lines.push('RRULE:' + rrule);
      const alertMinutes = Number(event.alert_minutes);
      if (Number.isFinite(alertMinutes) && alertMinutes >= 0) {
        lines.push('BEGIN:VALARM', 'ACTION:DISPLAY', 'DESCRIPTION:Reminder', 'TRIGGER:-PT' + Math.floor(alertMinutes) + 'M', 'END:VALARM');
      }
      lines.push('END:VEVENT');
    });
    lines.push('END:VCALENDAR');
    return lines.join('\r\n') + '\r\n';
  }

  function _icalUnescape(value) {
    return String(value || '')
      .replace(/\\n/gi, '\n')
      .replace(/\\,/g, ',')
      .replace(/\\;/g, ';')
      .replace(/\\\\/g, '\\');
  }

  function _icalDateValue(value, dateOnly) {
    const raw = String(value || '').trim();
    let match = raw.match(/^(\d{4})(\d{2})(\d{2})$/);
    if (match) return `${match[1]}-${match[2]}-${match[3]}`;
    if (dateOnly) return raw;
    match = raw.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})?(Z)?$/);
    if (!match) return raw;
    const [, y, mo, d, h, mi, s, z] = match;
    if (z) return new Date(Date.UTC(Number(y), Number(mo) - 1, Number(d), Number(h), Number(mi), Number(s || 0))).toISOString();
    return `${y}-${mo}-${d}T${h}:${mi}:${s || '00'}`;
  }

  function _parseIcalEvents(text) {
    const lines = [];
    String(text || '').split(/\r?\n/).forEach((line) => {
      if (/^[ \t]/.test(line) && lines.length) lines[lines.length - 1] += line.slice(1);
      else lines.push(line);
    });
    const events = [];
    let current = null;
    lines.forEach((line) => {
      const idx = line.indexOf(':');
      const prop = idx >= 0 ? line.slice(0, idx) : line;
      const name = prop.split(';')[0].toUpperCase();
      const isDateOnly = /;VALUE=DATE/i.test(prop);
      const value = idx >= 0 ? line.slice(idx + 1) : '';
      if (name === 'BEGIN' && value.toUpperCase() === 'VEVENT') {
        current = {};
        return;
      }
      if (name === 'END' && value.toUpperCase() === 'VEVENT') {
        if (current) events.push(current);
        current = null;
        return;
      }
      if (!current) return;
      if (name === 'UID') {
        current.uid = _icalUnescape(value);
        current.ical_uid = current.uid;
      }
      if (name === 'SUMMARY') current.title = _icalUnescape(value);
      if (name === 'DESCRIPTION') current.description = _icalUnescape(value);
      if (name === 'DTSTART') current.start = _icalDateValue(value, isDateOnly);
      if (name === 'DTEND') current.end = _icalDateValue(value, isDateOnly);
      if (name === 'LOCATION') current.location = _icalUnescape(value);
      if (name === 'URL') current.url = _icalUnescape(value);
      if (name === 'RRULE') current.recurrence = _rruleToRecurrenceJson(value);
      if (name === 'TRIGGER') {
        const match = String(value || '').match(/-?PT(\d+)([MH])/i);
        if (match) current.alert_minutes = Number(match[1]) * (match[2].toUpperCase() === 'H' ? 60 : 1);
      }
    });
    return events.filter(event => event.start || event.title || event.uid);
  }

  async function _importCalendarStoreIcs(provider, body) {
    const events = _parseIcalEvents(body?.ics || body?.content || '');
    const rows = await _readStore(provider, 'events');
    let imported = 0;
    let updated = 0;
    const user = String(body?.user || body?.creator || 'anonymous');
    events.forEach((event) => {
      const uid = String(event.uid || '').trim();
      const idx = uid ? rows.findIndex(row => row.ical_uid === uid || row.uid === uid || row.id === uid) : -1;
      const row = {
        id: idx >= 0 ? rows[idx].id : (uid || _randomId('events')),
        uid,
        ical_uid: event.ical_uid || uid,
        title: event.title || '無題',
        start: event.start || '',
        end: event.end || event.start || '',
        all_day: /^\d{4}-\d{2}-\d{2}$/.test(String(event.start || '')),
        description: event.description || '',
        location: event.location || '',
        url: event.url || '',
        recurrence: event.recurrence || '',
        alert_minutes: Number.isFinite(Number(event.alert_minutes)) ? Number(event.alert_minutes) : -1,
        calendar_id: body?.calendar_id || 'default',
        user,
        creator: user,
        modified: _nowIso(),
      };
      if (idx >= 0) {
        rows[idx] = { ...rows[idx], ...row };
        updated += 1;
      } else {
        rows.push({ created: _nowIso(), ...row });
        imported += 1;
      }
    });
    await _writeStore(provider, 'events', rows);
    return { ok: true, imported, updated };
  }

  async function _importCalendarDbIcs(provider, body) {
    const dbPath = _normalizeFolderPath(body?.db_path || body?.path || '');
    if (!dbPath) throw new Error('db_path は必須です');
    await _ensureFolderNote(provider, dbPath, 'calendar-db');
    const events = _parseIcalEvents(body?.ics || body?.content || '');
    const existing = await _calendarDbEvents(provider, dbPath).catch(() => []);
    let imported = 0;
    let updated = 0;
    for (const event of events) {
      const uid = String(event.uid || '').trim();
      const found = uid ? existing.find(row => row.ical_uid === uid || row.uid === uid) : null;
      const payload = {
        db_path: dbPath,
        title: event.title || '無題',
        uid,
        ical_uid: event.ical_uid || uid,
        start: event.start || '',
        end: event.end || event.start || '',
        all_day: /^\d{4}-\d{2}-\d{2}$/.test(String(event.start || '')),
