// Generated by cloud_standalone_apps.py. Do not edit the built copy.
const MELDEX_STANDALONE_APP_ID = "sheet";
const MELDEX_STANDALONE_APP_NAME = "Meldex Sheet";
const CACHE_PREFIX = "meldex-sheet-shell-";
const CACHE_NAME = CACHE_PREFIX + "0.6.185";
const APP_SHELL = new URL('./', self.location.href).href;
const API_PREFIX = new URL('../../api/', self.location.href).pathname;
const SHELL_ASSET_PATHS = Object.freeze(["./", "../../apps/sheet/manifest.webmanifest", "../../MeldexSheet_icon_256.png", "../../MeldexSheet_icon_64.png", "../../gb-fonts.css", "../../gb-icon-assets.css", "../../gb-theme.css", "../../gb-ui.css", "../../standalone-shell.css", "../../standalone-workspace-tree.css", "../../sheet-standalone.css", "../../gb-cloud-runtime-config.js", "../../gb-config.js", "../../gb-runtime-adapter.js", "../../gb-resource-url.js", "../../gb-dropbox-auth.js", "../../gb-source-folder-registry.js", "../../offline-bundles/gb-storage-adapter.js", "../../offline-bundles/gb-data-access.js", "../../gb-owner-key-store.js", "../../gb-knowledge-signature.js", "../../gb-file-lock-store.js", "../../gb-active-lock-store.js", "../../gb-active-locks.js", "../../offline-bundles/gb-data-access-dropbox-expanded.js", "../../offline-bundles/gb-data-access-dropbox-fileops.js", "../../vendor/lucide-icons.js", "../../offline-bundles/meldex-core.js", "../../gb-icon-assets.js", "../../standalone-stubs.js", "../../standalone-file-fs.js", "../../standalone-default-apps.js", "../../standalone-cloud-path-policy.js", "../../standalone-cloud-edit-session.js", "../../standalone-cloud-runtime.js", "../../standalone-workspace-tree.js", "../../standalone-pwa-install.js", "../../sheet-standalone-app.js", "../../fonts/NotoSansJP-Regular.woff2", "../../fonts/NotoSansJP-Medium.woff2", "../../fonts/NotoSansJP-Bold.woff2", "../../fonts/NotoColorEmoji_WindowsCompatible.ttf", "../../gb-ui.part01.css", "../../gb-ui.part04.css", "../../gb-ui.part02.css", "../../gb-ui.part03.css", "../../gb-ui.part01.part01.css", "../../gb-ui.part01.part02.css", "../../gb-ui.part04.part01.css", "../../gb-ui.part04.part02.css", "../../gb-ui.part02.part01.css", "../../gb-ui.part02.part02.css", "../../MeldexSheet_icon_512.png"]);
const SHELL_ASSETS = Object.freeze(SHELL_ASSET_PATHS.map((path) => new URL(path, self.location.href).href));
const SHELL_ASSET_PATHNAMES = new Set(SHELL_ASSETS.map((url) => new URL(url).pathname));
const STATIC_DESTINATIONS = new Set(['script', 'style', 'font', 'image', 'manifest', 'worker']);

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(SHELL_ASSETS.map((url) => new Request(url, { cache: 'reload' }))))
      .then(() => self.skipWaiting())
      .catch((error) => {
        console.error(MELDEX_STANDALONE_APP_NAME + ': shell cache failed', error);
        throw error;
      })
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys
        .filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME)
        .map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  const requestUrl = new URL(event.request.url);
  const scopeUrl = new URL('./', self.location.href);
  if (requestUrl.origin !== scopeUrl.origin || requestUrl.pathname.startsWith(API_PREFIX)) return;

  if (event.request.mode === 'navigate') {
    if (!requestUrl.pathname.startsWith(scopeUrl.pathname)) return;
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          if (response && response.ok) {
            caches.open(CACHE_NAME)
              .then((cache) => cache.put(APP_SHELL, response.clone()))
              .catch((error) => console.warn(MELDEX_STANDALONE_APP_NAME + ': shell update failed', error));
          }
          return response;
        })
        .catch(() => caches.match(APP_SHELL).then((cached) => cached || Response.error()))
    );
    return;
  }

  if (!SHELL_ASSET_PATHNAMES.has(requestUrl.pathname) && !STATIC_DESTINATIONS.has(event.request.destination)) return;
  event.respondWith(
    caches.match(event.request, { ignoreSearch: true }).then((cached) => cached || fetch(event.request).then((response) => {
      if (response && response.ok) {
        caches.open(CACHE_NAME)
          .then((cache) => cache.put(event.request, response.clone()))
          .catch((error) => console.warn(MELDEX_STANDALONE_APP_NAME + ': asset cache failed', error));
      }
      return response;
    }))
  );
});
